[build]
builder = "NIXPACKS"
buildCommand = "pip install -r backend/requirements.txt"

[deploy]
startCommand = "cd backend && python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10